### ISSUE TITLE
Some invalidity

### ISSUE THREAD

**Issue by kovalensky** [27justin/ohmyech#2]
If I use https://encryptedsni.com/cdn-cgi/trace the lock icon turns green for a moment, then switches back to red.

Is this behaviour normal?

**Comment by 27justin** [comment]
Hey @kovalensky, thank you for the report.

This is expected behaviour.
From what I can tell right now [https://encryptedsni.com/cdn-cgi/trace](https://encryptedsni.com/cdn-cgi/trace) itself loads over ECH while a subsequent request to [https://www.cloudflare.com/ssl/encrypted-sni/](https://www.cloudflare.com/ssl/encrypted-sni/) does not.
This appears to happen as the browser tries to fetch the favicon from encryptedsni.com, the server however redirects to the above Cloudflare domain, which in turn does not use ECH, invalidating the lock.

Though, looking at this, I think I'd be better off introducing a transitory state where an orange lock is displayed if only a subset of a page's request is using ECH.

**Comment by 27justin** [comment]
I've added the functionality in 3ca8002.
I'll be testing it out for a bit and then hopefully move the changes to the add-on registry by next week.

**Comment by kovalensky** [comment]
Dazzling! Perhaps, since the technology is not widespread yet, there should be some other state for sites loaded with the ECH but with insecure resource requests instead of red?

https://github.com/27justin/ohmyech/blob/3ca80025ecacf8a71ad934a3d841cb09545bd91c/README.org?plain=1#L24-L27

**Comment by 27justin** [comment]
I like the idea, will be looking into that tomorrow.

**Comment by 27justin** [comment]
Hey, added the functionality in 7545a29, thanks for the report & ideas.
Will be submitting the changes to the extension store either today or tomorrow.

**Comment by kovalensky** [comment]
@27justin Thanks for the feature and quick response 🤚🏻
